Repository googleapis/java-errorreporting, pull requests merged in 2020-12, with the labels that each got.

#327 chore: remove deprecated ErrorGroupServiceClient#getGroup(GroupName g…
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/it/ITSystemTest.java
Labels: api: clouderrorreporting, cla: yes

#332 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: full

#331 chore: Re-generated to pick up changes from googleapis.
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorGroupServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorGroupServiceSettings.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceSettings.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceSettings.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/package-info.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ErrorGroupServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ErrorGroupServiceStubSettings.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ErrorStatsServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ErrorStatsServiceStubSettings.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorGroupServiceCallableFactory.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorGroupServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorStatsServiceCallableFactory.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorStatsServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcReportErrorsServiceCallableFactory.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcReportErrorsServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ReportErrorsServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ReportErrorsServiceStubSettings.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/ErrorGroupServiceClientTest.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceClientTest.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockErrorGroupService.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockErrorGroupServiceImpl.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockErrorStatsService.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockErrorStatsServiceImpl.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockReportErrorsService.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockReportErrorsServiceImpl.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceClientTest.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceSmokeTest.java
  proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ErrorGroupName.java
  proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ProjectName.java
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: partial

#337 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#338 chore: migrate to microgenerator
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorGroupServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorGroupServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorStatsServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcReportErrorsServiceStub.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/ErrorGroupServiceClientTest.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceClientTest.java
  google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceClientTest.java
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full, lang: java

#349 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#350 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#351 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#335 chore: debrand Stackdriver from Error reporting sample
  .github/CODEOWNERS
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/errorreporting/QuickStart.java
Labels: api: clouderrorreporting, cla: yes, priority: p2, samples, type: docs

#353 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: partial
