Repository googleapis/java-errorreporting, pull requests merged in 2020-10, with the labels that each got.

#248 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#252 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#257 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#263 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#264 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#267 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#262 chore: add api-logging to codeowners
  .github/CODEOWNERS
  .repo-metadata.json
  CONTRIBUTING.md
  README.md
Labels: api: clouderrorreporting, cla: yes, lang: java, priority: p2

#274 chore: regenerate common templates
  .github/CODEOWNERS
  .github/snippet-bot.yml
  CONTRIBUTING.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#266 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#280 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#283 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#286 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#278 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#289 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#290 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
