Repository googleapis/java-errorreporting, pull requests merged in 2021-01, with the labels that each got.

#355 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#356 chore: update gapic-generator-java to 0.0.18
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorGroupServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorGroupServiceSettings.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceSettings.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceClient.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceSettings.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ErrorGroupServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ErrorStatsServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorGroupServiceCallableFactory.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorGroupServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorStatsServiceCallableFactory.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorStatsServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcReportErrorsServiceCallableFactory.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcReportErrorsServiceStub.java
  google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/ReportErrorsServiceStub.java
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: full

#361 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#362 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#368 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#371 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#373 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#374 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#376 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: clouderrorreporting, cla: yes
