Repository googleapis/java-errorreporting, pull requests merged in 2021-09, with the labels that each got.

#664 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: clouderrorreporting, automerge, context: full

#666 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, kokoro:force-run, api: clouderrorreporting, automerge, context: full

#637 chore: update gapic-generator-java version to 2.1.0
  google-cloud-errorreporting/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/stub/ErrorGroupServiceStubSettings.java
  google-cloud-errorreporting/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/stub/ErrorStatsServiceStubSettings.java
  google-cloud-errorreporting/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/stub/ReportErrorsServiceStubSettings.java
  synth.metadata
Labels: cla: yes, api: clouderrorreporting, context: full

#669 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: clouderrorreporting, context: full

#671 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: clouderrorreporting, automerge

#674 chore(fix): fix nightly test of samples
  samples/pom.xml
Labels: cla: yes, api: clouderrorreporting, samples, owlbot:ignore

#690 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: clouderrorreporting, automerge

#683 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: clouderrorreporting, automerge

#695 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: clouderrorreporting, automerge
