Repository googleapis/java-errorreporting, pull requests merged in 2021-05, with the labels that each got.

#522 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: none

#523 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: clouderrorreporting, automerge, cla: yes

#524 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: full

#530 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#534 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#535 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#536 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#538 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#539 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#541 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#544 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: full

#547 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#549 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes
