Repository googleapis/java-errorreporting, pull requests merged in 2021-08, with the labels that each got.

#601 ci: remove java 7 units check
  .github/sync-repo-settings.yaml
Labels: api: clouderrorreporting, cla: yes

#609 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: clouderrorreporting, automerge, cla: yes

#611 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#600 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#610 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: api: clouderrorreporting, automerge, cla: yes

#615 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: clouderrorreporting, automerge, cla: yes

#620 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting

#621 chore: sort imports in samples
  samples/snippets/src/main/java/com/example/errorreporting/QuickStart.java
Labels: cla: yes, api: clouderrorreporting, automerge, samples

#629 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting, automerge

#632 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting, automerge

#633 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: clouderrorreporting, automerge, context: full

#635 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting, automerge

#636 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting, automerge

#642 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: clouderrorreporting, automerge

#644 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting, automerge

#650 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting, automerge

#651 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting, automerge

#653 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: clouderrorreporting, automerge, context: full

#662 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: clouderrorreporting, automerge
